subroutine inputdata

! read the mesh generated by GID and takes nodal coordinates, and nodes from elements
! print the info in a text call elements and nodes


use vars 


character*11 texto     
open(10,file='Boundary_mesh.txt',status='unknown')! Open the file with coordinates and elements 

texto='1234567890&'
a1=1

nn=120 !number of boundary nodes. It must be change in every new problem

ne=nn/2
    
write(*,*)'The number of boundary elements is:',ne

allocate(coord(nn,2))     !number of nodes
allocate(conect(ne,3))    !number of conectivities in every element

do while (a1==1)
  read(10,*)texto
  if (texto=='Coordinates')a1=0
enddo


do i=1,nn
  read(10,*)dummy,coord(i,1),coord(i,2),dummy !Read the cordinates in each node,ignores Dummy
enddo

open(11,file='Nodes and elements.txt',status='unknown') !Create Nodes and elements file

do i=1,nn 
  write(11,*)i,coord(i,1),coord(i,2) !Print the coordinates in the file
enddo

!Does the same with elements.

a1=1

do while(a1==1)
  read(10,*)texto
  if(texto=='Elements   ')a1=0
enddo    

do i=1,ne
  read(10,*)dummy,conect(i,1),conect(i,3),conect(i,2)
enddo
  
do i=1,ne
  write(11,*)i,conect(i,3),conect(i,2),conect(i,1)
enddo

close(10)

close(11)

end
